[package]
name = "aoc2020"
version = "0.1.0"
authors = ["Ben Clarke <ben@arrayofstars.com>"]
edition = "2018"

[workspace]

members = [
    "util",
    "day1_1",
    "day1_2",
    "day2_1",
    "day2_2",
    "day3",
]